name: 'Rein Marriot '
favicon: null
layout_spectrum: 0.014337804401293397
typography_spectrum: 0.9817970397416502
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5a7294'
    - '#0d150a'
    - '#ffffbf'
    - '#b8c6c9'
    - '#b17847'
  brandStrength: 0.75
  lightness: 0.7756487955339253
  saturation: 0.2764406513888389
  rhythmicContrast: 0.3891884880140424
purpose: []
