name: 'Rein Marriot '
favicon: null
layout_spectrum: 0.73725
typography_spectrum: 0.4264
title: Aaron Ward/Tobais Ward/Wayne Ward/Nathan Luker
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5a7294'
    - '#0d150a'
    - '#ffffbf'
    - '#b8c6c9'
    - '#b17847'
  brandStrength: 0.875
  lightness: 0.7756487955339253
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
