name: 'Rein Marriot '
favicon: null
layout_spectrum: 0.32614
typography_spectrum: 0.4264
title: Rein Marriot.  Aaron Ward/Tobias Ward/Wayne Ward/Nathan Luker
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1c1f26'
    - '#646466'
    - '#949341'
    - '#deb48a'
  brandStrength: 1
  lightness: 0.7756487955339253
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
